server:
  #port: 8080
  address: 0.0.0.0

spring:
  mvc:
    cors:
      enabled: true
      mapping: /api/v1/chat/**
      allowed-origins:
        - http://chat.jjclub.pe.kr
        - ws://chat.jjclub.pe.kr
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
